[postgres]
host = "postgresql"
port = "5432"
user = "universityct"
password = "***REMOVED***"
name = "universityct"
connection_max = 10

[hermes]
api_key = "***REMOVED***"

[pprof]
    [pprof.rutgers-nk]
    host = "0.0.0.0:13301"
    enabled = true

    [pprof.rutgers-cm]
    host = "0.0.0.0:13302"
    enabled = true

    [pprof.rutgers-nb]
    host = "0.0.0.0:13303"
    enabled = true

    [pprof.spike]
    host = "0.0.0.0:13400"
    enabled = true

    [pprof.hermes]
    host = "0.0.0.0:13200"
    enabled = true

    [pprof.influx-logger]
    host = "0.0.0.0:13500"
    enabled = true

    [pprof.ein]
    host = "0.0.0.0:13100"
    enabled = true

[scrapers]
    [scrapers.rutgers-cm]
    interval = "1m"

    [scrapers.rutgers-nb]
    interval = "2m"

    [scrapers.rutgers-nk]
    interval = "1m"

[influxdb]
host = "influxdb"
user = "admin"
port =  "8086"
password = "***REMOVED***_influx"

[redis]
host = "redis"
port =  "6379"
db = 0
password = ""

[all]
loglevel = "debug"