[postgres]
host = "thirteen.tevindev.me"
port = "5432"
user = "postgres"
password = "***REMOVED***"
name = "universityct"
connection_max = 50

[hermes]
api_key = "***REMOVED***"

[pprof]
    [pprof.rutgers]
    host = "localhost:13300"
    enabled = true

    [pprof.spike]
    host = "localhost:13400"
    enabled = true

    [pprof.hermes]
    host = "localhost:13200"
    enabled = true

    [pprof.influx-logger]
    host = "localhost:13500"
    enabled = true

    [pprof.ein]
    host = "localhost:13100"
    enabled = true

[scrapers]
    [scrapers.rutgers-cm]
    interval = "1m"

    [scrapers.rutgers-nb]
    interval = "2m"

    [scrapers.rutgers-nk]
    interval = "1m"

[influx]
host = "http://thirteen.tevindev.me:8086"
user = "admin"
password = "***REMOVED***"

[redis]
host = "localhost"
port =  "32770"
db = 0
password = ""