[postgres]
host = "foreman.tevindev.me"
port = "5432"
user = "uct"
password = "***REMOVED***"
name = "universityct"
connection_max = 50

[hermes]
api_key = "***REMOVED***"

[pprof]
    [pprof.rutgers-nk]
    host = "localhost:13301"
    enabled = true

    [pprof.rutgers-cm]
    host = "localhost:13302"
    enabled = true

    [pprof.rutgers-nb]
    host = "localhost:13303"
    enabled = true

    [pprof.spike]
    host = "localhost:13400"
    enabled = true

    [pprof.hermes]
    host = "localhost:13200"
    enabled = true

    [pprof.influx-logger]
    host = "localhost:13500"
    enabled = true

    [pprof.ein]
    host = "localhost:13100"
    enabled = true

[scrapers]
    [scrapers.rutgers-cm]
    interval = "1m"

    [scrapers.rutgers-nb]
    interval = "2m"

    [scrapers.rutgers-nk]
    interval = "1m"

[influxdb]
host = "localhost"
user = "admin"
port =  "8086"
password = "***REMOVED***"

[redis]
host = "localhost"
port =  "6379"
db = 0
password = ""

[all]
loglevel = "debug"