[postgres]
host = "localhost"
port = "5432"
user = "universityct"
password = "universityct"
name = "universityct"
connection_max = 10

[hermes]
api_key = ""

[spike]
redis_db = 1

[redis]
host = "localhost"
port =  "6379"
db = 0
password = ""